export const connectorFormFields = [
  {
    id: 0,
    name: "Amazon S3 to BigQuery Connector",
    type: "source",
    source: "Amazon S3",
    destination: "Google BigQuery",
    authentication: {
      apiKey: "abc123xyz789",
      username: "admin_user",
      password: "secure_password",
      token: "Bearer xyz123token",
    },
    configuration: {
      endpoint: "https://s3.amazonaws.com/my-bucket",
      port: "443",
      databaseName: "bigquery-dataset",
      tableName: "customer_data",
      schema: "public",
      fileFormat: "CSV",
      batchSize: "1000",
    },
    scheduling: {
      frequency: "Daily",
      cronExpression: "0 12 * * *",
    },
    status: "active",
    createdAt: "2025-03-20 17:44",
  },
  {
    id: 1,
    name: "Google Drive to Amazon S3 Sync",
    type: "destination",
    source: "Google Drive",
    destination: "Amazon S3",
    authentication: {
      oauthToken: "drive-oauth-token",
    },
    configuration: {
      folderId: "1a2b3cDriveFolder",
      fileType: "PDF",
      destinationBucket: "s3://backup-drive-bucket",
      syncMode: "incremental",
    },
    scheduling: {
      frequency: "Hourly",
      cronExpression: "0 * * * *",
    },
    status: "active",
    createdAt: "2025-03-21 10:00",
  },
  {
    id: 2,
    name: "Google Sheets to PostgreSQL Sync",
    type: "source",
    source: "Google Sheets",
    destination: "PostgreSQL",
    authentication: {
      oauthToken: "sheets-oauth-token",
    },
    configuration: {
      spreadsheetId: "spreadsheet12345",
      sheetName: "CustomerData",
      databaseUrl: "postgresql://db.example.com:5432",
      tableName: "customers",
      batchSize: "500",
    },
    scheduling: {
      frequency: "Weekly",
      cronExpression: "0 0 * * 0",
    },
    status: "pending",
    createdAt: "2025-03-22 08:30",
  },
  {
    id: 3,
    name: "Google Docs to Notion Sync",
    type: "source",
    source: "Google Docs",
    destination: "Notion",
    authentication: {
      oauthToken: "docs-notion-token",
    },
    configuration: {
      documentId: "doc12345",
      notionPageId: "notion-page-abc",
      syncType: "full",
    },
    scheduling: {
      frequency: "Every 6 hours",
      cronExpression: "0 */6 * * *",
    },
    status: "active",
    createdAt: "2025-03-23 12:15",
  },
  {
    id: 4,
    name: "Slack Messages to Google Sheets",
    type: "source",
    source: "Slack",
    destination: "Google Sheets",
    authentication: {
      apiKey: "slack-api-key-xyz",
    },
    configuration: {
      channelId: "C123456",
      spreadsheetId: "spreadsheet67890",
      sheetName: "Messages",
      messageFormat: "plain_text",
    },
    scheduling: {
      frequency: "Real-time",
      cronExpression: "* * * * *",
    },
    status: "active",
    createdAt: "2025-03-24 09:45",
  },
  {
    id: 5,
    name: "Jira Issues to Trello Board",
    type: "destination",
    source: "Jira",
    destination: "Trello",
    authentication: {
      username: "jira_admin",
      apiToken: "jira-api-token-987",
    },
    configuration: {
      jiraProjectId: "PRJ-001",
      trelloBoardId: "trello-board-xyz",
      syncLabels: true,
    },
    scheduling: {
      frequency: "Every 2 hours",
      cronExpression: "0 */2 * * *",
    },
    status: "inactive",
    createdAt: "2025-03-25 14:20",
  },
  {
    id: 6,
    name: "PostgreSQL to Google BigQuery Data Pipeline",
    type: "source",
    source: "PostgreSQL",
    destination: "Google BigQuery",
    authentication: {
      databaseUser: "db_user",
      databasePassword: "secure_db_pass",
    },
    configuration: {
      databaseUrl: "postgresql://db.example.com:5432",
      tableName: "sales_data",
      bigQueryDataset: "sales_dataset",
      syncMethod: "incremental",
    },
    scheduling: {
      frequency: "Daily",
      cronExpression: "0 3 * * *",
    },
    status: "active",
    createdAt: "2025-03-26 11:10",
  },
  {
    id: 7,
    name: "Google Analytics to Google Sheets Report",
    type: "destination",
    source: "Google Analytics",
    destination: "Google Sheets",
    authentication: {
      oauthToken: "ga-oauth-token",
    },
    configuration: {
      viewId: "ga123456",
      metrics: ["pageviews", "sessions", "bounceRate"],
      dimensions: ["date", "source", "medium"],
      spreadsheetId: "spreadsheet-analytics",
      sheetName: "GA Reports",
    },
    scheduling: {
      frequency: "Daily",
      cronExpression: "0 6 * * *",
    },
    status: "active",
    createdAt: "2025-03-27 07:30",
  },
];
